"""empty message

Revision ID: 335c946fe62d
Revises: 49cea0a0d926
Create Date: 2020-09-03 23:34:09.006084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335c946fe62d'
down_revision = '49cea0a0d926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_response',
    sa.Column('response_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('trial_number', sa.Integer(), nullable=True),
    sa.Column('recorded_response', sa.String(length=50), nullable=True),
    sa.Column('expected_response', sa.String(length=50), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('response_id')
    )
    # op.drop_table('sqlite_sequence')
    op.drop_table('response')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('response_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('trial_number', sa.INTEGER(), nullable=True),
    sa.Column('recorded_response', sa.VARCHAR(length=50), nullable=True),
    sa.Column('expected_response', sa.VARCHAR(length=50), nullable=True),
    sa.Column('correct', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('correct IN (0, 1)'),
    sa.PrimaryKeyConstraint('response_id')
    )
    # op.create_table('sqlite_sequence',
    # sa.Column('name', sa.NullType(), nullable=True),
    # sa.Column('seq', sa.NullType(), nullable=True)
    # )
    op.drop_table('model_response')
    # ### end Alembic commands ###
