"""empty message

Revision ID: 49cea0a0d926
Revises: 
Create Date: 2020-09-03 23:02:52.935304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49cea0a0d926'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('response_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('trial_number', sa.Integer(), nullable=True),
    sa.Column('recorded_response', sa.String(length=50), nullable=True),
    sa.Column('expected_response', sa.String(length=50), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_table('trail',
    sa.Column('trail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(length=50), nullable=True),
    sa.Column('word', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('trail_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # op.drop_table('sqlite_sequence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('sqlite_sequence',
    # sa.Column('name', sa.NullType(), nullable=True),
    # sa.Column('seq', sa.NullType(), nullable=True)
    # )
    op.drop_table('user')
    op.drop_table('trail')
    op.drop_table('response')
    # ### end Alembic commands ###
